#!/usr/bin/env zsh
setopt ERR_EXIT EXTENDED_GLOB

# ----------------------------------------------------------------------
# Storage initialization commmands
# Dell XPS 13 (2015) Pure Arch Install Script
# Will be using SATA hw based encryption, so no LUKS
# Going for a pure btrfs UEFI install, single partition
# ----------------------------------------------------------------------
# curl -LO http://links.ethanschoonover.com/archinit


# Scorched earth - erase all GPT and MBR structures
# Make EFI system partition
# Make swap partition
# Make system partition
sgdisk -zog $CONFIG[drive]
sgdisk --new=1:0:+512M -c 1:"EFI System Partition" -t 1:ef00 $CONFIG[drive]
sgdisk --new=2:0:+$(( $(print ${$(cat /proc/meminfo | grep -i memtotal)[2]}) / 1000000 ))G -c 2:"Swap Partition" -t 2:8200 $CONFIG[drive]
sgdisk --new=3:0:0 -c 3:"Linux System Partition" -t 3:8304 $CONFIG[drive]

# Format EFI system partition
# Format swap partition
# Format system partition
mkfs.fat -F32 --label EFI $CONFIG[drive]1
mkswap -L Swap $CONFIG[drive]2
mkfs.btrfs --force --label System $CONFIG[drive]3

# Activate swap
# Mount filesystem
o=defaults,x-mount.mkdir
o_btrfs=$o,compress=lzo,space_cache,autodefrag,inode_cache,ssd,discard
swapon -d -L Swap
mount -o $o -L System /mnt
mount -o $o -L EFI /mnt/boot

# Install base system
pacstrap /mnt base base-devel zsh
